travis:
  secure:
    BINSTAR_TOKEN: CDh+gHnS6c+lN2Du8VIX++rgl2oXAZxx926gtbbCO77kbCd1b18cVtd8a58/rVmHdWEdb0KtpIFttXeRMldl4B4URgj92jNP6p/xmFo7PFiu3CjFIL3+5ZiOVjOnyytmumD+I8r7im2LCGbtoLz7RJoojVGLnM6Rba5S94xZD2a7QBB1bDZ4qr1NoX2U4NUdnGv0MfI8/ZgIc7WNRz7j7HQ3STpdIQVYElznJVprG1Y025637fvF22ADozm3j79JOkQ7/9+dTCC8OOsu7z6F4aPjApXAJV8TVR8yjPPmE/4+zZwRblVGQuBKBuYh1DkHTTGFaTF3DvfcmiPiBjJDq/th42ZbU0awy4UAivGDvnA0gYkMckkjtOIy6z2qZpAjsjLLXR5lRofX8gFPZVr3IYnB4ZO2TbfAtu3uteU8tLPcT+WrsgR5sP8da+J9z+YCwY4RohI6VsDFkvnfxGiX42ve9M8R/PGe2PZfCHBLjMDjWAzLZ3hIrcgvTqZNsZMbsyl4ZMT9id6saw45AcLbVP9UIGDMsxuE0xtpwCEF9ePPkPGqy/63a0B/abagFSzacgRqo0iUGykN5j79OITkmfnvyN82Qhh8AnVuU6MbEr2VzIWTJ6eioFVuARi5rBgGTrUp8dwC98FCNp08wTOpgSAiLix8if36UF+R2EP+RMY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
