travis:
  secure:
    BINSTAR_TOKEN: jqGBPRdD0o6Rlqyg/gSzZO+ivNj6oQmCWSwD6MINRlgqH6LiuYWi9EOTQW8OClMAswFhl/XNxqjhRXIfG/P7BfmDHAYRqb45wkbRVVU6iOof2n4UDVZsIzq5r5QUSSP7WfL/poTL7ANIJWneWYXGwBHjsoy7K62Z2GUXYFvCK71mg6WUGtyVoYlL9+JXND3ssk8LFL8MBk9/TZ4ONU5KFqUXwyaDxSBApKj6wnAF95LN8eOKINQufVqZ2jwtMrmrKuoA4e1g47YFOBvO7Rv0FHM1n1I+F0+0f8RX8eT0/kN8DxL8rGdKUseMevcWfw4vXzJvnsTQ2smNlqBFNBzrDodsVdkd9KJ/79doNHxqlOTt4TbRukqrMZ97gPLTyxo/o6znhkqWsJpZyLguW56/8eyalXoFlUyvQAtwIOvXzrOnI1AlVNRUh6kLwkDihP5FAd9P+VITn+Qmlk/AGifhmI7bDFPjUlPbV3w8S2aG0C/BZK9atI/d8Gt/C9JRx/14syqJQ5XWptVUi6btZ90hu9Sph03yNKTGHi1ZjBEmHnOXcA39F+OM1yIVmWfuzhg4uz1CmHnk86BsXv05QuNHBTnjOKLukd8VMgHPdyJzxDDEl9nF8QutQH3ejWA5UdWP/reKdgohCkgKW24NiTZa6FC7G3X8BS97rQjJkHBmpvM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
