travis:
  secure:
    BINSTAR_TOKEN: SnHQc1AwQnHeXARI5bFyONAM4Uge3n/aFb0ld/I5xwtMz9SCwN2D41tN3JRt2Jj315LIGGnJj4z2SwzsFXwVtn6mIXJabHvXCgHlveIsgFJSaBkA61l04hls3mrxC4Dg4AxgaVBqU14wTrFM1iPToTgGffI2Jgj8yHt26NnNt3JzBNbORuDp6RVp6y7uYPUHQJUSU7Dzk3KMPDIgiZMOjPxnWbPzfUyLkp/8LI8fbHzEGf3Yaskk0VmWqCsHoqb/r1yXL52+CudaD2ByC9Ua8y/ixQVprhR+yb089zeQ0Wl1hnk8yJkkhfWhhESdIB/TlbYCqmf1B2TPfcUMcDU0QHN8CUYKPK52A6q9Tz1SpqrZfSM2rQudGXMLG9HyQ3r6fg5vZbfVqZSF52bz9hag30drv16rYUkwZiG7KGKY7PF/lr3KLVx/6zqbY4wiQnNBjBwUZG/QOITjaX3Ul6LJ8tvtJIGRDzRYD0pqQt/6au/X7js3rIctyO/0006NI74lz8En858gX3E0kLrzpHIaMinR7l6ma7itbHd6bxu6zcuAokJFGPmHWSF0vN6WJUv0qNYYrBqmKUb9CyX+RW3PTGHz3bFvN5kDYzEv+1EX/T4DnRzcLOWcN/xPLPVRR/SLq5UKIv20ga9uhO9fnboXBpgtEuhX6eoyarZmWdBr/BU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
